### ISSUE TITLE
Open to PR for expo/camera?  

### ISSUE THREAD

**Issue by desmond-dsouza** [fxfactorial/bs-expo#1]
I will be doing a Reason wrapper for this (and probably more expo/* stuff later), let me know if you are open to a PR.

**Comment by fxfactorial** [comment]
Of course!

**Comment by desmond-dsouza** [comment]
Great!

Any guidelines on how you’d want the PR be tested? I’m quite unsure how to write tests for RN code.

**Comment by fxfactorial** [comment]
Add code testing and consuming your new APIs in the test-app.
