### ISSUE TITLE
Goals for this Library

### ISSUE THREAD

**Issue by fiber-god** [fxfactorial/bs-expo#13]
I think we should take the development of the library (at least initially) to a point where every API is bound to and looks nearly identical to the JS Expo SDK. That will make it easy for people just starting out with Reason & Expo and reduce the amount of documentation that will need to be written. Also, it will make it easier to track the JS Expo SDK's changes. I suggest we start versioning based on Expo releases when we get a fully-featured "1.0" state as well to make it easier for Expo users to reason about which version of this library to use.

**Comment by fxfactorial** [comment]
Agree
