### ISSUE TITLE
Bring up to Expo SDK 31

### ISSUE THREAD

**Issue by lewisf** [fxfactorial/bs-expo#18]
SDK 25 is getting dropped soon, so it might be worth bringing this up to date?

I also think it'd be great if the major versions of this repo matched the expo sdk repo?

Thoughts? I'd be happy to help out.

**Comment by fxfactorial** [comment]
Sorry, this repo un maintained now

**Comment by FiberJW** [comment]
@lewisf check out https://github.com/FiberJW/reason-expo for a more comprehensive set of bindings for Expo 👌

**Comment by lewisf** [comment]
sweet, thank you!
