### ISSUE TITLE
bsb fails on current npm version

### ISSUE THREAD

**Issue by desmond-dsouza** [fxfactorial/bs-expo#2]
Wanted to use your Permissions.re to develop Camera.re:

```
Air:medley> npm install bs-expo --save
medley@0.1.0 .../medley
└── bs-expo@0.0.2 
(added to bsconfig.json)
Air:medley> bsb -make-world
Error: ... medley/node_modules/bs-expo/src/private: No such file or directory
```

Any pointers? Also, do you prefer these to be asked elsewhere e.g. on Reason Discord?

**Comment by fxfactorial** [comment]
Oh that's odd. Maybe should publish a version where it doesn't do that. You can ask wherever you like :) 

I'll be giving this lib some more attention on this coming Sunday

**Comment by desmond-dsouza** [comment]
:) Sunday sounds great. I am curious what might cause the “private” dir to be totally missing from what npm installs.

**Comment by fxfactorial** [comment]
Also confused about that, but just published a version without it

**Comment by FiberJW** [comment]
Closing until further issues arise
