### ISSUE TITLE
Reformat File Names to More Idiomatic ReasonML Conventions?

### ISSUE THREAD

**Issue by fiber-god** [fxfactorial/bs-expo#6]
Hey there,

I'd suggest that the file names start with a capital letter so that they can map 1-1 to their module name used in the code. The official [ReasonML Docs](https://reasonml.github.io/docs/en/project-structure.html#file-casing) suggest it as well, and I think it would be good for newcomers that might get confused with the odd capitalization (like `aV.re` when it's referred to as `AV` in the code).

This suggestion wouldn't change functionality at all and it wouldn't break anything. It would just make the codebase more readable and approachable.

If you agree with my suggestion, I can send a PR renaming the files.

Thanks!

**Comment by fxfactorial** [comment]
Hmm, but aV.re will become AV as a module, you just want to change it to AV.re? 

Sure, I will give commit access and you do as you see fit
